name: vehicle_management_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cloud_firestore: ^5.5.0
  dartz: ^0.10.1
  dio: ^5.7.0
  dropdown_button2: ^2.3.9
  equatable: ^2.0.5
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.14
  geocoding: ^3.0.0
  get_it: ^8.0.2
  go_router: ^14.6.0
  google_api_headers: ^4.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.10.0
  # google_maps_place_picker_mb: ^3.1.2
  http: ^1.2.2
  hydrated_bloc: ^9.1.5
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  location: ^6.0.2
  logger: ^2.5.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mockito: ^5.0.16
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/fonts/
    - assets/animations/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Satoshi
  #     fonts:
  #       - asset: assets/fonts/Satoshi-Black.ttf
  #         weight: 900
  #       - asset: assets/fonts/Satoshi-Bold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Satoshi-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Satoshi-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Satoshi-Light.ttf
  #         weight: 300

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
